import os
from datetime import datetime

class FileManager:
    def __init__(self, base_folder: str):
        self.base_folder = base_folder
        os.makedirs(base_folder, exist_ok=True)
    
    def save_conversation(self, title: str, messages: list) -> str:
        """Save conversation as plain text"""
        safe_title = title.lower().replace(" ", "_").replace("/", "-")
        filename = f"{self.base_folder}/{safe_title}_{datetime.now().strftime('%Y%m%d_%H%M')}.txt"
        
        with open(filename, "w", encoding="utf-8") as f:
            f.write(f"Travel & Retirement Plan: {title}\n")
            f.write(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}\n\n")
            
            for msg in messages:
                if isinstance(msg, dict):
                    if msg.get("role") == "system":
                        continue
                    role = msg.get("role", "UNKNOWN").upper()
                    content = msg.get("content", str(msg))
                else:
                    if getattr(msg, "role", None) == "system":
                        continue
                    role = getattr(msg, "role", "UNKNOWN").upper()
                    content = getattr(msg, "content", str(msg))
                
                f.write(f"{role}:\n{content}\n\n")
        
        return filename
    
    def export_markdown(self, title: str, messages: list) -> str:
        """Export as nicely formatted Markdown"""
        safe_title = title.lower().replace(" ", "_").replace("/", "-")
        filename = f"{self.base_folder}/{safe_title}_{datetime.now().strftime('%Y%m%d_%H%M')}.md"
        
        with open(filename, "w", encoding="utf-8") as f:
            f.write(f"# {title}\n\n")
            f.write(f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M')}\n\n")
            f.write("---\n\n")
            
            for msg in messages:
                if isinstance(msg, dict):
                    if msg.get("role") == "system":
                        continue
                    role = msg.get("role", "").upper()
                    content = msg.get("content", str(msg))
                else:
                    if getattr(msg, "role", None) == "system":
                        continue
                    role = getattr(msg, "role", "").upper()
                    content = getattr(msg, "content", str(msg))
                
                if role == "USER":
                    f.write(f"## 👤 Question\n{content}\n\n")
                else:
                    f.write(f"## 🤖 Agent Response\n{content}\n\n")
                    f.write("---\n\n")
            
            f.write("\n*Generated by Smart Travel & Retirement Agent*\n")
        
        print(f"✅ Markdown exported: {filename}")
        return filename